spring:
  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  flyway:
    enabled: false

jwt:
  secret: dGVzdFNlY3JldEtleUZvclVuaXRUZXN0aW5nT25seTIwMjQ=
  expiration: 3600000
